# Generated by Django 3.2.6 on 2022-12-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20221219_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
